INSERT INTO USER (USER_ID, LOGIN_ID, PASSWORD) VALUES (1, 'admin', '$2a$10$Lo5i/br.gVwhz/gH1HFiUeP2Oa3NYUFf/nCFjqkSQAkWiVcLldY6G');
INSERT INTO USER (USER_ID, LOGIN_ID, PASSWORD) VALUES (2, 'user', '$2a$10$3NvNSBbRrtPvJ71kIk./Pe3qeEZr9lzRwXU3kqQy.28PILiD7PpEC');




